export const IMAGE_SOURCE = "https://image.tmdb.org/t/p/w500";

export const movies = [
  {
    adult: false,
    backdrop_path: "/ovM06PdF3M8wvKb06i4sjW3xoww.jpg",
    genre_ids: [878, 12, 28],
    id: 76600,
    original_language: "en",
    original_title: "Avatar: The Way of Water",
    overview:
      "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    popularity: 6789.789,
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    release_date: "2022-12-14",
    title: "Avatar: The Way of Water",
    video: false,
    vote_average: 7.7,
    vote_count: 6098,
  },
  {
    adult: false,
    backdrop_path: "/wD2kUCX1Bb6oeIb2uz7kbdfLP6k.jpg",
    genre_ids: [27, 53],
    id: 980078,
    original_language: "en",
    original_title: "Winnie the Pooh: Blood and Honey",
    overview:
      "Christopher Robin is headed off to college and he has abandoned his old friends, Pooh and Piglet, which then leads to the duo embracing their inner monsters.",
    popularity: 3258.54,
    poster_path: "/fNTtVbqI92abEKAgz2ynurCUne.jpg",
    release_date: "2023-01-27",
    title: "Winnie the Pooh: Blood and Honey",
    video: false,
    vote_average: 5.9,
    vote_count: 234,
  },
  {
    adult: false,
    backdrop_path: "/i8dshLvq4LE3s0v8PrkDdUyb1ae.jpg",
    genre_ids: [28, 53, 80],
    id: 603692,
    original_language: "en",
    original_title: "John Wick: Chapter 4",
    overview:
      "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    popularity: 2803.482,
    poster_path: "/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg",
    release_date: "2023-03-22",
    title: "John Wick: Chapter 4",
    video: false,
    vote_average: 8.2,
    vote_count: 471,
  },
  {
    adult: false,
    backdrop_path: "/a2tys4sD7xzVaogPntGsT1ypVoT.jpg",
    genre_ids: [53, 35, 80, 27],
    id: 804150,
    original_language: "en",
    original_title: "Cocaine Bear",
    overview:
      "Inspired by a true story, an oddball group of cops, criminals, tourists and teens converge in a Georgia forest where a 500-pound black bear goes on a murderous rampage after unintentionally ingesting cocaine.",
    popularity: 2781.045,
    poster_path: "/gOnmaxHo0412UVr1QM5Nekv1xPi.jpg",
    release_date: "2023-02-22",
    title: "Cocaine Bear",
    video: false,
    vote_average: 6.6,
    vote_count: 531,
  },
  {
    adult: false,
    backdrop_path: "/ouB7hwclG7QI3INoYJHaZL4vOaa.jpg",
    genre_ids: [16, 12, 35, 10751],
    id: 315162,
    original_language: "en",
    original_title: "Puss in Boots: The Last Wish",
    overview:
      "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
    popularity: 1531.792,
    poster_path: "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
    release_date: "2022-12-07",
    title: "Puss in Boots: The Last Wish",
    video: false,
    vote_average: 8.3,
    vote_count: 4883,
  },
  {
    adult: false,
    backdrop_path: "/2Eewgp7o5AU1xCataDmiIL2nYxd.jpg",
    genre_ids: [18, 36],
    id: 943822,
    original_language: "en",
    original_title: "Prizefighter: The Life of Jem Belcher",
    overview:
      "At the turn of the 19th century, Pugilism was the sport of kings and a gifted young boxer fought his way to becoming champion of England.",
    popularity: 1400.798,
    poster_path: "/x3PIk93PTbxT88ohfeb26L1VpZw.jpg",
    release_date: "2022-06-30",
    title: "Prizefighter: The Life of Jem Belcher",
    video: false,
    vote_average: 6.2,
    vote_count: 93,
  },
  {
    adult: false,
    backdrop_path: "/sp7MPK2K60LLd7A6zjHKsfgjFil.jpg",
    genre_ids: [27, 53],
    id: 296271,
    original_language: "en",
    original_title: "The Devil Conspiracy",
    overview:
      "The hottest biotech company in the world has discovered they can clone history’s most influential people from the dead. Now, they are auctioning clones of Michelangelo, Galileo, Vivaldi, and others for tens of millions of dollars to the world’s ultra-rich. But when they steal the Shroud of Turin and clone the DNA of Jesus Christ, all hell breaks loose.",
    popularity: 1280.108,
    poster_path: "/2lUYbD2C3XSuwqMUbDVDQuz9mqz.jpg",
    release_date: "2023-01-13",
    title: "The Devil Conspiracy",
    video: false,
    vote_average: 6.4,
    vote_count: 63,
  },
  {
    adult: false,
    backdrop_path: "/m1fgGSLK0WvRpzM1AmZu38m0Tx8.jpg",
    genre_ids: [28],
    id: 842945,
    original_language: "en",
    original_title: "Supercell",
    overview:
      "Good-hearted teenager William always lived in hope of following in his late father’s footsteps and becoming a storm chaser. His father’s legacy has now been turned into a storm-chasing tourist business, managed by the greedy and reckless Zane Rogers, who is now using William as the main attraction to lead a group of unsuspecting adventurers deep into the eye of the most dangerous supercell ever seen.",
    popularity: 1249.672,
    poster_path: "/gbGHezV6yrhua0KfAgwrknSOiIY.jpg",
    release_date: "2023-03-17",
    title: "Supercell",
    video: false,
    vote_average: 6.1,
    vote_count: 19,
  },
  {
    adult: false,
    backdrop_path: "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
    genre_ids: [28, 12, 878],
    id: 505642,
    original_language: "en",
    original_title: "Black Panther: Wakanda Forever",
    overview:
      "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
    popularity: 1203.24,
    poster_path: "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
    release_date: "2022-11-09",
    title: "Black Panther: Wakanda Forever",
    video: false,
    vote_average: 7.3,
    vote_count: 4320,
  },
  {
    adult: false,
    backdrop_path: "/zM9RGbJBZ3UNpFOabcRqh0iVAYP.jpg",
    genre_ids: [27, 9648, 53],
    id: 631842,
    original_language: "en",
    original_title: "Knock at the Cabin",
    overview:
      "While vacationing at a remote cabin, a young girl and her two fathers are taken hostage by four armed strangers who demand that the family make an unthinkable choice to avert the apocalypse. With limited access to the outside world, the family must decide what they believe before all is lost.",
    popularity: 1192.041,
    poster_path: "/dm06L9pxDOL9jNSK4Cb6y139rrG.jpg",
    release_date: "2023-02-01",
    title: "Knock at the Cabin",
    video: false,
    vote_average: 6.4,
    vote_count: 1143,
  },
  {
    adult: false,
    backdrop_path: "/coWUgAjqwyu2W7YFlb71rlukPKZ.jpg",
    genre_ids: [],
    id: 1076605,
    original_language: "en",
    original_title: "Cazadora",
    overview:
      "Psychological thriller where the character's strength, submerged in the landscape's majesty, leads us through a tense, bleak and chilling path.",
    popularity: 1084.456,
    poster_path: "/p0pvd23j7yA9aJzB6EatoblJ3kO.jpg",
    release_date: "2023-01-19",
    title: "Cazadora",
    video: false,
    vote_average: 6.6,
    vote_count: 5,
  },
  {
    adult: false,
    backdrop_path: "/eNJhWy7xFzR74SYaSJHqJZuroDm.jpg",
    genre_ids: [28, 878],
    id: 1033219,
    original_language: "en",
    original_title: "Attack on Titan",
    overview:
      "As viable water is depleted on Earth, a mission is sent to Saturn's moon Titan to retrieve sustainable H2O reserves from its alien inhabitants. But just as the humans acquire the precious resource, they are attacked by Titan rebels, who don't trust that the Earthlings will leave in peace.",
    popularity: 1056.236,
    poster_path: "/ay8SLFTMKzQ0i5ewOaGHz2bVuZL.jpg",
    release_date: "2022-09-30",
    title: "Attack on Titan",
    video: false,
    vote_average: 6.4,
    vote_count: 19,
  },
  {
    adult: false,
    backdrop_path: "/9Rq14Eyrf7Tu1xk0Pl7VcNbNh1n.jpg",
    genre_ids: [28, 12, 53],
    id: 646389,
    original_language: "en",
    original_title: "Plane",
    overview:
      "After a heroic job of successfully landing his storm-damaged aircraft in a war zone, a fearless pilot finds himself between the agendas of multiple militias planning to take the plane and its passengers hostage.",
    popularity: 1001.16,
    poster_path: "/qi9r5xBgcc9KTxlOLjssEbDgO0J.jpg",
    release_date: "2023-01-12",
    title: "Plane",
    video: false,
    vote_average: 6.9,
    vote_count: 978,
  },
  {
    adult: false,
    backdrop_path: "/7eccX0xay9pDj6ZQvU4cu3whw18.jpg",
    genre_ids: [16, 14, 27],
    id: 1003579,
    original_language: "en",
    original_title: "Batman: The Doom That Came to Gotham",
    overview:
      "Explorer Bruce Wayne accidentally unleashes an ancient evil, and returns to Gotham after being away for two decades. There, Batman battles Lovecraftian supernatural forces and encounters allies and enemies such as Green Arrow, Ra's al Ghul, Mr. Freeze, Killer Croc, Two-Face and James Gordon.",
    popularity: 978.014,
    poster_path: "/hrATQE8ScQceohwInaMluluNEaf.jpg",
    release_date: "2023-03-10",
    title: "Batman: The Doom That Came to Gotham",
    video: false,
    vote_average: 6.3,
    vote_count: 40,
  },
  {
    adult: false,
    backdrop_path: "/ve3RLbCSuUKA02OZJ5F0fMmXVMn.jpg",
    genre_ids: [27, 53],
    id: 829410,
    original_language: "en",
    original_title: "Sick",
    overview:
      "In the midst of the pandemic, college student Parker and her best friend Miri decide to self-quarantine at her family's lake house, where they will be alone — or so they think.",
    popularity: 968.185,
    poster_path: "/nBgxSimgLMGYCQckRQw7C2f7row.jpg",
    release_date: "2022-09-11",
    title: "Sick",
    video: false,
    vote_average: 6.3,
    vote_count: 120,
  },
  {
    adult: false,
    backdrop_path: "/sGE6N1vJjxZLkOJEXdIOqTslxuL.jpg",
    genre_ids: [99],
    id: 1087040,
    original_language: "en",
    original_title: "Money Shot: The Pornhub Story",
    overview:
      "Featuring interviews with performers, activists and past employees, this documentary offers a deep dive into the successes and scandals of Pornhub.",
    popularity: 935.276,
    poster_path: "/g7fD1EHgctNSjBUzAOfxEsHaB2k.jpg",
    release_date: "2023-03-15",
    title: "Money Shot: The Pornhub Story",
    video: false,
    vote_average: 5.8,
    vote_count: 108,
  },
  {
    adult: false,
    backdrop_path: "/ql4PnvKYKaMtdx9Ck4fHY2wJphT.jpg",
    genre_ids: [35, 18, 10749],
    id: 32516,
    original_language: "cn",
    original_title: "金瓶梅2 愛的奴隸",
    overview:
      "Rich and powerful Simon Qing has been schooled in the ways of sex by his virile father, but is still a virgin. That is, until he meets his first love Violetta who has fun with him all over his father’s estate. Their love does not last, so Simon embarks on a journey. Along the way he meets the comely nun Moon whom Simon deflowers and then marries. He then becomes enamored of Golden Lotus but she is married to dwarf Wu Da-Lang.",
    popularity: 929.318,
    poster_path: "/A1yymig7S0FTWv9cTtOwdI1cH5V.jpg",
    release_date: "2009-03-04",
    title: "The Forbidden Legend: Sex & Chopsticks 2",
    video: false,
    vote_average: 6,
    vote_count: 60,
  },
  {
    adult: false,
    backdrop_path: "/qai0MnVwPYCwOPSAnHIHyzBVqnd.jpg",
    genre_ids: [16, 12, 10751, 14],
    id: 776835,
    original_language: "en",
    original_title: "The Magician's Elephant",
    overview:
      "Peter is searching for his long-lost sister when he crosses paths with a fortune teller in the market square. His one one question is: is his sister still alive? The answer, that he must find a mysterious elephant and the magician who will conjure it, sets Peter off on a journey to complete three seemingly impossible tasks that will change the face of his town forever.",
    popularity: 923.055,
    poster_path: "/cAoAgzOCxSytYBqqCQulhXNR3LB.jpg",
    release_date: "2023-03-10",
    title: "The Magician's Elephant",
    video: false,
    vote_average: 7.4,
    vote_count: 63,
  },
  {
    adult: false,
    backdrop_path: "/muw9YsAsSd3DDRme2OEJJoVqun9.jpg",
    genre_ids: [53, 28],
    id: 850871,
    original_language: "es",
    original_title: "Sayen",
    overview:
      "Sayen is hunting down the men who murdered her grandmother. Using her training and knowledge of nature, she is able to turn the tables on them, learning of a conspiracy from a corporation that threatens her people's ancestral lands.",
    popularity: 917.859,
    poster_path: "/aCy61aU7BMG7SfhkaAaasS0KzUO.jpg",
    release_date: "2023-03-03",
    title: "Sayen",
    video: false,
    vote_average: 6.2,
    vote_count: 64,
  },
  {
    adult: false,
    backdrop_path: "/r17jFHAemzcWPPtoO0UxjIX0xas.jpg",
    genre_ids: [28, 53, 80],
    id: 324552,
    original_language: "en",
    original_title: "John Wick: Chapter 2",
    overview:
      "John Wick is forced out of retirement by a former associate looking to seize control of a shadowy international assassins’ guild. Bound by a blood oath to aid him, Wick travels to Rome and does battle against some of the world’s most dangerous killers.",
    popularity: 894.616,
    poster_path: "/hXWBc0ioZP3cN4zCu6SN3YHXZVO.jpg",
    release_date: "2017-02-08",
    title: "John Wick: Chapter 2",
    video: false,
    vote_average: 7.3,
    vote_count: 11166,
  },
];
